extends Node

# Sinais existentes...
signal player_try_harvest(harvest_position: Vector2, player_direction: Vector2)
signal resource_collected(resource_type: String, amount: int, position: Vector2)
signal player_direction_changed(new_direction: Vector2)
signal day_started(day_number: int)
signal night_started()
signal fire_energy_changed(current: float, max: float)
signal game_over(reason: String)
signal victory(reason: String)
signal building_constructed(building_type: String)
signal building_damaged(building_type: String, damage: int)
signal build_menu_toggled()
signal building_mode_started()
signal building_mode_ended()
signal building_selected(building_type: String)

# Novos sinais do GDD avançado
signal fire_low_warning(energy_percent: float)
signal fire_critical()
signal fire_level_changed(level: int)
signal player_status_changed(health: float, hunger: float, cold: float)
signal player_died()
signal player_attacked(damage: int)
signal shadow_damaged(damage: int)
signal wood_used(amount: int)
signal food_used(amount: int)
signal npc_spawned(count: int)
signal npc_died(reason: String)
signal temperature_changed(temperature: float)
