extends Node

# Sinais existentes...
signal player_try_harvest(harvest_position: Vector2, player_direction: Vector2)
signal resource_collected(resource_type: String, amount: int, position: Vector2)
signal player_direction_changed(new_direction: Vector2)
signal day_started(day_number: int)
signal night_started()
signal fire_energy_changed(current: float, max: float)
signal game_over(reason: String)
signal victory(reason: String)
signal building_constructed(building_type: String)
signal building_damaged(building_type: String, damage: int)
signal build_menu_toggled()
signal building_mode_started()
signal building_mode_ended()
signal building_selected(building_type: String)

# Novos sinais do GDD avançado
signal fire_low_warning(energy_percent: float)
signal fire_critical()
signal fire_level_changed(level: int)
signal player_status_changed(health: float, hunger: float, cold: float)
signal player_died()

signal player_hit(damage : float)
signal hideWarning(type: String)
signal showWarning(message:String,type:String)
signal player_attacked(damage: int)
signal shadow_damaged(damage: int)
signal wood_used(amount: int)
signal food_used(amount: int)
signal npc_spawned(count: int)
signal npc_died(reason: String)
signal temperature_changed(temperature: float)

signal planting_mode_changed(is_active: bool)
signal seed_type_changed(seed_type: String)
signal seed_planted(seed_type: String, position: Vector2)

#Adiciona os sinais ao grupo de usuário para evitar erro
func _ready() -> void:
	add_user_signal("player_try_harvest")
	add_user_signal("player_direction_changed")
	add_user_signal("day_started")
	add_user_signal("night_started")
	add_user_signal("fire_energy_changed")
	add_user_signal("game_over")
	add_user_signal("victory")
	add_user_signal("building_constructed")
	add_user_signal("building_damaged")
	add_user_signal("build_menu_toggled")
	add_user_signal("building_mode_started")
	add_user_signal("building_mode_ended")
	add_user_signal("building_selected")
	add_user_signal("fire_low_warning")
	add_user_signal("fire_critical")
	add_user_signal("fire_level_changed")
	add_user_signal("player_status_changed")
	add_user_signal("player_died")
	add_user_signal("player_attacked")
	add_user_signal("shadow_damaged")
	add_user_signal("wood_used")
	add_user_signal("food_used")
	add_user_signal("npc_spawned")
	add_user_signal("npc_died")
	add_user_signal("temperature_changed")
	add_user_signal("planting_mode_changed")
	add_user_signal("seed_type_changed")
	add_user_signal("seed_planted")
	
